### ISSUE TITLE
Capture class, "TypeError: Parameter must be callable"

### ISSUE THREAD

**Issue by jonathan-99** [jonathan-99/anemometer#13]
# Execution error for Capture Class.

When executed from [Capture.py|https://github.com/jonathan-99/anemometer/blob/development-general/Capture.py] I get the following error:
```
GPIO.add_event_callback(17, self.WindEventHandler())
"TypeError: Parameter must be callable"
```

**Comment by combivanCoder** [comment]
Suspect the callback is asking for a method rather than the result of a method so it might be worth trying:
`GPIO.add_event_callback(17, self.WindEventHandler)`

**Comment by jonathan-99** [comment]
Executes now, trying to identify output.
